/**
 * schools.js
 * Source-of-truth school data for Laser2Uni.
 * Owner: data person
 *
 * New fields (2025 update):
 *   admitRate       - overall transfer admit rate as decimal
 *   tagGpa          - TAG GPA requirement, or null if no TAG
 *   tagExclusions   - array of major strings excluded from TAG
 *   majorMinGpa     - object mapping major names to their minimum GPA
 *   competitiveness - integer 1-5 per major group (1=Accessible, 5=Highly Selective)
 */

const SCHOOLS = [
  {
    id: 'uci',
    name: 'UC Irvine',
    short: 'UCI',
    loc: 'Irvine, CA',
    type: 'UC',
    emoji: '🔵',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/300.png',
    size: 'Large',
    minGPA: 3.4,
    selectivity: 4,
    admitRate: 0.395,
    tagGpa: 3.4,
    tagExclusions: [
      'Business Administration',
      'Nursing',
      'Nursing / Pre-Nursing',
      'Computer Science',
      'Software Engineering',
      'Informatics',
      'Computer Engineering'
    ],
    majorMinGpa: {
      'Business Administration': 3.0,
      'Nursing': 3.0,
      'Nursing / Pre-Nursing': 3.0,
      'Computer Science': 3.0,
      'Computer Engineering': 3.0,
      'Mechanical Engineering': 3.0,
      'Psychology': 3.0,
      'Biology': 3.0,
      'Education': 3.0,
      'Economics': 2.8,
      'Communication': 2.7,
      'default': 2.4
    },
    competitiveness: {
      'Computer Science': 5,
      'Nursing': 5,
      'Nursing / Pre-Nursing': 5,
      'Business Administration': 5,
      'Computer Engineering': 4,
      'Mechanical Engineering': 4,
      'Biology': 4,
      'default': 3
    },
    tagline: 'Top STEM + business',
    tags: ['TAG Eligible', 'IVC Honors to UCI', 'Research'],
    regions: ['SoCal'],
    strengths: ['Tech / Software', 'Engineering / Hardware', 'Research / Academia', 'Healthcare / Medicine', 'Education', 'History'],
    ivcPerks: 'IVC has a direct Honors-to-Honors articulation with UCI. TAG guarantees admission if you meet the GPA threshold for your major. Being 10 minutes away means a strong transfer community.'
  },
  {
    id: 'ucb',
    name: 'UC Berkeley',
    short: 'UCB',
    loc: 'Berkeley, CA',
    type: 'UC',
    emoji: '🐻',
    logo: 'assets/logos/BERK LOGO.png',
    size: 'Large',
    minGPA: 3.7,
    selectivity: 5,
    admitRate: 0.24,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.5 },
    competitiveness: { 'default': 5 },
    tagline: 'Top public university in the world',
    tags: ['Highly Selective', 'Research', 'Top Ranked', 'Prestigious', 'TAP Honors'],
    regions: ['NorCal / Bay Area'],
    strengths: ['Tech / Software', 'Engineering / Hardware', 'Research / Academia', 'Business / Finance', 'Government / Policy', 'Healthcare / Medicine'],
    ivcPerks: 'TAP Honors to Honors available: 3.5 GPA UC-transferable, 3.25 in honors coursework. No TAG but TAP gives IVC Honors students a real pathway.'
  },
  {
    id: 'ucla',
    name: 'UC Los Angeles',
    short: 'UCLA',
    loc: 'Los Angeles, CA',
    type: 'UC',
    emoji: '🟡',
    logo: 'assets/logos/UCLA 2 LOGO.png',
    size: 'Large',
    minGPA: 3.7,
    selectivity: 5,
    admitRate: 0.227,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.5 },
    competitiveness: {
      'Computer Science': 5,
      'Nursing': 5,
      'Nursing / Pre-Nursing': 5,
      'Business Administration': 5,
      'Engineering': 5,
      'Mechanical Engineering': 5,
      'Electrical Engineering': 5,
      'default': 5
    },
    tagline: 'Prestige + massive network',
    tags: ['Highly Selective', 'Research', 'Top Ranked'],
    regions: ['SoCal'],
    strengths: ['Tech / Software', 'Business / Finance', 'Research / Academia', 'Creative / Media', 'Startups / Entrepreneurship', 'Education', 'History']
  },
  {
    id: 'ucsd',
    name: 'UC San Diego',
    short: 'UCSD',
    loc: 'La Jolla, CA',
    type: 'UC',
    emoji: '🌊',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/28.png',
    size: 'Large',
    minGPA: 3.5,
    selectivity: 4,
    admitRate: 0.527,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.0 },
    competitiveness: {
      'Computer Science': 5,
      'Electrical Engineering': 4,
      'Mechanical Engineering': 4,
      'Biology': 4,
      'Pre-Med / Biology': 4,
      'default': 3
    },
    tagline: 'Top biotech + CS',
    tags: ['Biotech', 'Research-Heavy', 'Strong Transfer Pipeline'],
    regions: ['SoCal'],
    strengths: ['Engineering / Hardware', 'Healthcare / Medicine', 'Research / Academia', 'Tech / Software', 'History'],
    ivcPerks: 'Strong SoCal CC transfer pipeline with a 52.7% overall admit rate. World-class biotech, engineering, and CS programs.'
  },
  {
    id: 'ucsb',
    name: 'UC Santa Barbara',
    short: 'UCSB',
    loc: 'Santa Barbara, CA',
    type: 'UC',
    emoji: '🏖',
    logo: 'assets/logos/UCSB LOGO.png',
    size: 'Large',
    minGPA: 3.4,
    selectivity: 3,
    admitRate: 0.589,
    tagGpa: 3.4,
    tagExclusions: ['Computer Science'],
    majorMinGpa: {
      'Computer Science': 3.3,
      'Psychology': 3.3,
      'default': 2.8
    },
    competitiveness: {
      'Computer Science': 5,
      'default': 3
    },
    tagline: 'Research + beautiful campus',
    tags: ['TAG Eligible', 'Research', 'Social Scene'],
    regions: ['SoCal', 'NorCal / Bay Area'],
    strengths: ['Research / Academia', 'Tech / Software', 'Engineering / Hardware', 'History', 'Education'],
    ivcPerks: 'TAG eligible. Strong transfer acceptance culture and excellent transfer support services.'
  },
  {
    id: 'ucd',
    name: 'UC Davis',
    short: 'UCD',
    loc: 'Davis, CA',
    type: 'UC',
    emoji: '🐄',
    logo: 'assets/logos/UC DAVIS LOGO.png',
    size: 'Large',
    minGPA: 3.2,
    selectivity: 3,
    admitRate: 0.57,
    tagGpa: 3.2,
    tagExclusions: ['Computer Science', 'Data Science'],
    majorMinGpa: {
      'Mechanical Engineering': 3.5,
      'Electrical Engineering': 3.5,
      'Civil Engineering': 3.5,
      'Aerospace Engineering': 3.5,
      'Chemical Engineering': 3.5,
      'Biomedical Engineering': 3.5,
      'default': 3.0
    },
    competitiveness: {
      'Computer Science': 4,
      'Mechanical Engineering': 4,
      'Electrical Engineering': 4,
      'default': 3
    },
    tagline: 'Strong STEM + pre-med',
    tags: ['TAG Eligible', 'Pre-Med', 'Collaborative'],
    regions: ['NorCal / Bay Area'],
    strengths: ['Healthcare / Medicine', 'Research / Academia', 'Engineering / Hardware', 'Education', 'History'],
    ivcPerks: 'TAG eligible. Excellent TAG acceptance rate for transfers from SoCal CCs.'
  },
  {
    id: 'ucsc',
    name: 'UC Santa Cruz',
    short: 'UCSC',
    loc: 'Santa Cruz, CA',
    type: 'UC',
    emoji: '🌲',
    logo: 'assets/logos/UCSC LOGO.png',
    size: 'Medium',
    minGPA: 3.0,
    selectivity: 3,
    admitRate: 0.61,
    tagGpa: 3.0,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.0 },
    competitiveness: { 'default': 2 },
    tagline: 'CS powerhouse, tech ties',
    tags: ['TAG Eligible', 'CS-Strong', 'Nature Campus'],
    regions: ['NorCal / Bay Area'],
    strengths: ['Tech / Software', 'Research / Academia', 'Engineering / Hardware', 'History'],
    ivcPerks: 'TAG eligible. Very transfer-friendly. CS department has strong Silicon Valley recruiting pipelines.'
  },
  {
    id: 'ucr',
    name: 'UC Riverside',
    short: 'UCR',
    loc: 'Riverside, CA',
    type: 'UC',
    emoji: '🏜',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/27.png',
    size: 'Medium',
    minGPA: 2.8,
    selectivity: 2,
    admitRate: 0.682,
    tagGpa: 3.0,
    tagExclusions: [],
    majorMinGpa: { 'default': 2.8 },
    competitiveness: { 'default': 2 },
    tagline: 'Accessible UC, growing fast',
    tags: ['TAG Eligible', 'Pre-Med Friendly', 'Accessible'],
    regions: ['SoCal'],
    strengths: ['Healthcare / Medicine', 'Research / Academia', 'Engineering / Hardware', 'Education', 'History'],
    ivcPerks: 'One of the most transfer-friendly UCs. Very high TAG acceptance rate. Close to IVC - strong local community.'
  },
  {
    id: 'ucm',
    name: 'UC Merced',
    short: 'UCM',
    loc: 'Merced, CA',
    type: 'UC',
    emoji: '☀️',
    logo: 'assets/logos/ucm.png',
    size: 'Small',
    minGPA: 2.4,
    selectivity: 1,
    admitRate: 0.721,
    tagGpa: 3.0,
    tagExclusions: [],
    majorMinGpa: {
      'Biology': 2.9,
      'Pre-Med / Biology': 2.9,
      'default': 2.4
    },
    competitiveness: { 'default': 1 },
    tagline: 'Newest UC, small classes',
    tags: ['TAG Eligible', 'Scholarships', 'Small Classes'],
    regions: ['NorCal / Bay Area'],
    strengths: ['Research / Academia', 'Engineering / Hardware'],
    ivcPerks: 'Highest TAG acceptance rate of all UCs. Strong merit scholarships specifically for CC transfers.'
  },
  {
    id: 'csuf',
    name: 'Cal State Fullerton',
    short: 'CSUF',
    loc: 'Fullerton, CA',
    type: 'CSU',
    emoji: '🟠',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png',
    size: 'Large',
    minGPA: 2.5,
    selectivity: 1,
    admitRate: 0.55,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 2.5 },
    competitiveness: { 'default': 2 },
    tagline: 'Top business + film in OC',
    tags: ['Transfer-Friendly', 'Business', 'Film/Media'],
    regions: ['SoCal'],
    strengths: ['Business / Finance', 'Creative / Media', 'Government / Policy', 'Education', 'History']
  },
  {
    id: 'csulb',
    name: 'Cal State Long Beach',
    short: 'CSULB',
    loc: 'Long Beach, CA',
    type: 'CSU',
    emoji: '⚓',
    logo: 'assets/logos/CSULB LOGO 2.png',
    size: 'Large',
    minGPA: 2.7,
    selectivity: 2,
    admitRate: 0.56,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 2.7 },
    competitiveness: { 'default': 2 },
    tagline: 'Strong engineering + nursing',
    tags: ['Transfer-Friendly', 'Engineering', 'Diverse'],
    regions: ['SoCal'],
    strengths: ['Engineering / Hardware', 'Healthcare / Medicine', 'Business / Finance', 'Education', 'History']
  },
  {
    id: 'cpslo',
    name: 'Cal Poly SLO',
    short: 'Cal Poly',
    loc: 'San Luis Obispo, CA',
    type: 'CSU',
    emoji: '🏔',
    logo: 'assets/logos/SLO LOGO.png',
    size: 'Medium',
    minGPA: 3.3,
    selectivity: 3,
    admitRate: 0.78,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.3 },
    competitiveness: {
      'Computer Science': 4,
      'Mechanical Engineering': 4,
      'Electrical Engineering': 4,
      'default': 3
    },
    tagline: '"Learn by doing" - hands-on engineering',
    tags: ['Hands-On', 'Competitive CSU', 'Engineering'],
    regions: ['SoCal', 'NorCal / Bay Area'],
    strengths: ['Engineering / Hardware', 'Tech / Software', 'Startups / Entrepreneurship']
  },
  {
    id: 'sdsu',
    name: 'San Diego State',
    short: 'SDSU',
    loc: 'San Diego, CA',
    type: 'CSU',
    emoji: '🌴',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    size: 'Large',
    minGPA: 3.0,
    selectivity: 2,
    admitRate: 0.55,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.0 },
    competitiveness: { 'default': 2 },
    tagline: 'Strong business + campus life',
    tags: ['Transfer-Friendly', 'Business', 'Active Campus', 'Social Scene'],
    regions: ['SoCal'],
    strengths: ['Business / Finance', 'Creative / Media', 'Government / Policy', 'Education', 'History']
  },
  {
    id: 'cpp',
    name: 'Cal Poly Pomona',
    short: 'CPP',
    loc: 'Pomona, CA',
    type: 'CSU',
    emoji: '🌿',
    logo: 'assets/logos/CAL POLY POMONA LOGO.png',
    size: 'Large',
    minGPA: 2.6,
    selectivity: 1,
    admitRate: 0.71,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 2.6 },
    competitiveness: { 'default': 2 },
    tagline: 'Practical, industry-ready',
    tags: ['Transfer-Friendly', 'Engineering', 'Hands-On'],
    regions: ['SoCal'],
    strengths: ['Engineering / Hardware', 'Tech / Software', 'Business / Finance']
  },
  {
    id: 'sjsu',
    name: 'San Jose State',
    short: 'SJSU',
    loc: 'San Jose, CA',
    type: 'CSU',
    emoji: '💻',
    logo: 'assets/logos/SJSU LOGO.png',
    size: 'Large',
    minGPA: 3.0,
    selectivity: 2,
    admitRate: 0.60,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.0 },
    competitiveness: {
      'Computer Science': 4,
      'Mechanical Engineering': 3,
      'Electrical Engineering': 3,
      'default': 2
    },
    tagline: 'Silicon Valley campus',
    tags: ['Transfer-Friendly', 'Tech', 'Silicon Valley'],
    regions: ['NorCal / Bay Area'],
    strengths: ['Tech / Software', 'Engineering / Hardware', 'Business / Finance']
  },
  {
    id: 'usc',
    name: 'USC',
    short: 'USC',
    loc: 'Los Angeles, CA',
    type: 'Private',
    emoji: '⚔️',
    logo: 'assets/logos/USC LOGO.png',
    size: 'Large',
    minGPA: 3.8,
    selectivity: 5,
    admitRate: 0.271,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.44 },
    competitiveness: { 'default': 5 },
    tagline: 'Elite private, huge network',
    tags: ['Prestigious', 'Trojan Network', 'Selective'],
    regions: ['SoCal'],
    strengths: ['Business / Finance', 'Creative / Media', 'Engineering / Hardware', 'Tech / Software', 'Startups / Entrepreneurship']
  },
  {
    id: 'lmu',
    name: 'Loyola Marymount',
    short: 'LMU',
    loc: 'Los Angeles, CA',
    type: 'Private',
    emoji: '✨',
    logo: 'assets/logos/LOYOLA LOGO.png',
    size: 'Medium',
    minGPA: 3.2,
    selectivity: 3,
    admitRate: 0.60,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.2 },
    competitiveness: { 'default': 3 },
    tagline: 'Strong transfer + film + biz',
    tags: ['Transfer-Friendly', 'Private', 'Film/Business'],
    regions: ['SoCal'],
    strengths: ['Business / Finance', 'Creative / Media', 'Government / Policy']
  },
  {
    id: 'oc',
    name: 'Occidental College',
    short: 'Oxy',
    loc: 'Los Angeles, CA',
    type: 'Private',
    emoji: '🏛',
    logo: 'assets/logos/OCCIDENTAL LOGO.png',
    size: 'Small',
    minGPA: 3.5,
    selectivity: 3,
    admitRate: 0.45,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.5 },
    competitiveness: { 'default': 3 },
    tagline: 'Liberal arts, small & elite',
    tags: ['Small Classes', 'Liberal Arts', 'Private'],
    regions: ['SoCal'],
    strengths: ['Research / Academia', 'Government / Policy', 'Creative / Media']
  },
  {
    id: 'chapman',
    name: 'Chapman University',
    short: 'Chapman',
    loc: 'Orange, CA',
    type: 'Private',
    emoji: '🏛️',
    logo: 'assets/logos/CHAPMAN LOGO.png',
    size: 'Medium',
    minGPA: 3.2,
    selectivity: 3,
    admitRate: 0.60,
    tagGpa: null,
    tagExclusions: [],
    majorMinGpa: { 'default': 3.0 },
    competitiveness: { 'default': 3 },
    tagline: 'Strong film, business & pre-law',
    tags: ['Transfer-Friendly', 'Private', 'Film/Business'],
    regions: ['SoCal'],
    strengths: ['Business / Finance', 'Creative / Media', 'Government / Policy', 'Healthcare / Medicine'],
    ivcPerks: 'Located in Orange, CA - 15 minutes from IVC. Strong transfer acceptance and merit aid for CC students.'
  }
];
